language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  - "hhvm"

before_script:
  - composer self-update
  - composer dump-autoload -o
  - mkdir -p public/css
  - mkdir -p build/css && cd build/css curl -Lk https://gist.githubusercontent.com/unisys12/fd42d98347079a57c5e6/raw/d14d4d0c10ca2c44a7da254adab7781cef112a27/vertical-carousel.scss > test.css
  - cd ..

script: phpunit -c phpunit.xml

after_script:
  - rm -rf public/css
  - rm -rf build/css