language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  - "hhvm"

before_script:
  - composer self-update
  - composer dump-autoload -o
  - mkdir public/css/
  - touch build/css/test1.css

script: phpunit

after_script:
  - rm -rf public/css
  - rm -rf build/css