language: php
php:
  - "5.5"
  - "5.4"
  - "hhvm"

before_script:
  - composer self-update
  - composer dump-autoload -o
  - mkdir -p public/css 
  - cd /public 
  - curl -Lk https://gist.githubusercontent.com/unisys12/6b57fcb318317d0716ca/raw/6a300007c95ab438a38f0996ed3c1e6b64a8c183/gistfile1.txt > config.php
  - cd ..
  - mkdir -p build/css 
  - cd build/css 
  - curl -Lk https://gist.githubusercontent.com/unisys12/fd42d98347079a57c5e6/raw/d14d4d0c10ca2c44a7da254adab7781cef112a27/vertical-carousel.scss > test.css
  - cd $TRAVIS_BUILD_DIR

script: phpunit

after_script:
  - rm -rf public/css
  - rm -rf build/css